name: Deploy to Azure App Services

on:
  push:
    branches:
      - main
      - frontend

permissions:
  id-token: write
  contents: read
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_FRONTEND_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_FRONTEND_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_FRONTEND_REGISTRY_PASSWORD }}
      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.AZURE_FRONTEND_REGISTRY }}.azurecr.io/${{secrets.FRONTEND_IMAGE_NAME}}:latest
            ${{ secrets.AZURE_FRONTEND_REGISTRY }}.azurecr.io/${{secrets.FRONTEND_IMAGE_NAME}}:${{ github.sha }}
  redeploy_app_service:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_FRONTEND_CREDENTIALS }}
          enable-AzPSSession: true
      - name: Restart Azure App Service
        run: az webapp restart --name ${{ secrets.AZURE_FRONTEND_SERVICE_NAME }} --resource-group  ${{ secrets.AZURE_FRONTEND_RESOURCE_GROUP }}
